version: "3"

dotenv:
  - .env
  - .env.local

env:
  PORT: 8080

vars:
  container_name: app
  container_tag: latest

tasks:
  dev:
    run: always
    cmds:
      - $HOME/go/bin/air

  build:
    deps:
      - task: generate
    cmds:
      - CGO_ENABLED=0 go build -o build/server main.go

  container:
    deps:
      - task: generate
    cmds:
      - docker build -t {{.container_name}}:{{.container_tag}} .

  generate:
    aliases:
      - gen
      - g
    generates:
      - components/**/*.go
      - views/**/*.go
      - style/output.css
    sources:
      - components/**/*.templ
      - views/**/*.templ
      - style/tailwind.config.js
      - style/input.css
    cmds:
      - tailwindcss -i style/input.css -o style/output.css --minify
      - $HOME/go/bin/templ generate
      - go generate ./...