// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.833
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Footer() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<footer class=\"mt-auto text-center py-5\"><div class=\"max-w-7xl mx-auto px-4 sm:px-6 lg:px-8\"><p class=\"mt-3 text-lg text-gray-300\">Built with <img src=\"assets/svg/go.svg\" class=\"inline-block\" width=\"50px\">&nbsp;&nbsp;,&nbsp;&nbsp;<img src=\"assets/svg/echo.svg\" class=\"inline-block\" width=\"75px\">&nbsp;&nbsp;,&nbsp;&nbsp;<img src=\"assets/svg/templ.svg\" class=\"inline-block\" width=\"100px\">&nbsp;&nbsp;,&nbsp;&nbsp;<img src=\"assets/svg/htmx.svg\" class=\"inline-block\" width=\"100px\">&nbsp;&nbsp; . Deployed on <img src=\"assets/svg/azure.svg\" class=\"inline-block\" width=\"18px\">zure.</p></div></footer>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
