name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24" # Adjust Go version as needed

      - name: Build Docker Image
        run: |
          docker build -t personal-webpage:latest .

      - name: Log in to Docker Hub
        env:
          DOCKER_ACCESS_TOKEN: ${{ secrets.DOCKER_ACCESS_TOKEN }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: |
          echo "$DOCKER_ACCESS_TOKEN" | docker login -u "$DOCKER_USERNAME" --password-stdin

      - name: Tag and Push Docker Image to Docker Hub
        run: |
          docker tag personal-webpage:latest docker.io/${{ secrets.DOCKER_USERNAME }}/personal-webpage:latest
          docker push docker.io/${{ secrets.DOCKER_USERNAME }}/personal-webpage:latest

      - name: Setup SSH and Deploy to VPS
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          VPS_IP: ${{ secrets.VPS_IP }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H "$VPS_IP" >> ~/.ssh/known_hosts

          ssh -v webpage@"$VPS_IP" << 'EOF'
            docker login -u "${{ secrets.DOCKER_USERNAME }}" -p "${{ secrets.DOCKER_ACCESS_TOKEN }}"
            docker pull docker.io/${{ secrets.DOCKER_USERNAME }}/personal-webpage:latest
            docker stop personal-webpage || true
            docker rm personal-webpage || true
            docker run -d --name my-app -p 8080:80 --restart unless-stopped docker.io/${{ secrets.DOCKER_USERNAME }}/personal-webpage:latest
            EOF
