name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.24" # Set the Go version you need

      - name: Build Docker Image
        run: |
          docker build -t my-app:latest .

      - name: Push Docker Image to Registry (if needed)
        run: |
          echo "${{ secrets.DOCKER_ACCESS_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker tag my-app:latest my-registry.com/my-app:latest
          docker push my-registry.com/my-app:latest

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.VPS_IP }} >> ~/.ssh/known_hosts

      - name: Deploy to VPS
        run: |
          ssh webpage@${{ secrets.VPS_IP }} "
            docker pull my-registry.com/my-app:latest &&
            docker stop my-app || true &&
            docker rm my-app || true &&
            docker run -d --name my-app -p 80:80 my-registry.com/my-app:latest
          "
