name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24" # Adjust Go version as needed

      - name: Build Docker Image
        run: |
          docker build -t webpage:latest .
          docker images

      - name: Log in to Docker Hub
        env:
          DOCKER_ACCESS_TOKEN: ${{ secrets.DOCKER_ACCESS_TOKEN }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: |
          echo "$DOCKER_ACCESS_TOKEN" | docker login -u "$DOCKER_USERNAME" --password-stdin

      - name: Setup SSH and Deploy to VPS
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          VPS_IP: ${{ secrets.VPS_IP }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H "$VPS_IP" >> ~/.ssh/known_hosts

          ssh -v webpage@"$VPS_IP" "
            docker login -u '${{ secrets.DOCKER_USERNAME }}' -p '${{ secrets.DOCKER_ACCESS_TOKEN }}' &&
            docker pull ${{ secrets.DOCKER_USERNAME }}/webpage:latest &&
            docker stop webpage || true &&
            docker rm webpage || true &&
            docker run -d --name webpage -p 80:8080 --restart unless-stopped ${{ secrets.DOCKER_USERNAME }}/webpage:latest
          "
